version: '3.3'


services:
#  postgres:
#    image: postgres:13.1
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=student
#      - POSTGRES_DB=students
#    networks:
#      - msc
#    healthcheck:
#      test: [ "CMD", "psql", "-U", "student", "-d", "students" ]
#      interval: 500ms
#      timeout: 1s
#      retries: 5
#    volumes:
#      - dbdata:/var/lib/postgresql/data


#  students-schema-creation:
#    image: postgres:13.1
#    volumes:
#      - ./sql:/sql
#    environment:
#      DATABASE_NAME: students
#      DATABASE_USERNAME: student
#      DATABASE_PASSWORD: password
#      DATABASE_ENDPOINT: postgres
#      DATABASE_PORT: 5432
#    entrypoint: [ "/sql/create-schema.sh" ]
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - msc
#    command: [ "students" ]

  students-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
#    depends_on:
#      postgres:
#        condition: service_healthy
    command:
      - "--url=jdbc:postgresql://postgres:5432/students"
      - "--username=student"
      - "--password=password"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=students"
      - "update"
    networks:
      - msc

networks:
  msc:
    name: msc-localdev_msc
    driver: bridge
    external: true
