version: '3.3'

x-db-schema-creation: &db-schema-creation
  image: postgres:13.1
  volumes:
    - ./sql:/sql
  environment:
      DATABASE_NAME: students
      DATABASE_USERNAME: student
      DATABASE_PASSWORD: password
      DATABASE_ENDPOINT: postgres
      DATABASE_PORT: 5432
  entrypoint: ["/sql/create-schema.sh"]
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - msc


services:
  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=student
      - POSTGRES_DB=students
    networks:
      - msc
    healthcheck:
      test: [ "CMD", "psql", "-U", "student", "-d", "students" ]
      interval: 500ms
      timeout: 1s
      retries: 5



  students-schema-creation:
    <<: *db-schema-creation
    command: [ "studentsschema" ]

  timecard-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
    command:
      - "--url=jdbc:postgresql://postgres:5432/students"
      - "--username=student"
      - "--password=password"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=studentsschema"
      - "update"
    networks:
      - msc

networks:
  msc:
    driver: bridge
