version: '3.3'

services:

#  user-service:
#    build: .
#    ports:
#      - "9091:9091"
#    environment:
#      - POSTGRESHOST=postgres
#      - POSTGRESUSER=student
#      - POSTGRESPASSWORD=password
#    depends_on:
#      - users-database-migrations
#    networks:
#      - msc

  users-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
    command:
      - "--url=jdbc:postgresql://postgres:5432/mscstudents"
      - "--username=student"
      - "--password=password"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=users"
      - "update"
    networks:
      - msc

networks:
  msc:
    name: msc-localdev_msc
    driver: bridge
    external: true
